//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  Contract3.sol
//   Output filename: Contract3.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace Contract3
{
	#if UNITY_EDITOR || !ENABLE_MONO
	[BackedType(typeof(Contract3Backing))]
	#endif
	public interface Contract3 : IContract
	{
		[EvmConstructorMethod]
		Task<Contract3> DeployNew();
		
		[EvmMethodInfo(Name = "allTickets", View = true)]
		Task<BigInteger> AllTickets();
		
		[EvmMethodInfo(Name = "blast", View = true)]
		Task<EvmAddress> Blast();
		
		[EvmMethodInfo(Name = "deposit", View = false)]
		Task<Transaction> Deposit();
		
		[EvmMethodInfo(Name = "getAvailableYield", View = true)]
		Task<BigInteger> GetAvailableYield();
		
		[EvmMethodInfo(Name = "getBalance", View = true)]
		Task<BigInteger> GetBalance();
		
		[EvmMethodInfo(Name = "lastLotteryTimestamp", View = true)]
		Task<BigInteger> LastLotteryTimestamp();
		
		[EvmMethodInfo(Name = "lottery", View = false)]
		Task<Transaction> Lottery();
		
		[EvmMethodInfo(Name = "lotteryInterval", View = true)]
		Task<BigInteger> LotteryInterval();
		
		[EvmMethodInfo(Name = "playerTickets", View = true)]
		Task<BigInteger> PlayerTickets([EvmParameterInfo(Type = "address", Name = "")] EvmAddress address, CallOptions options = default);
		
		[EvmMethodInfo(Name = "withdraw", View = false)]
		Task<Transaction> Withdraw(BigInteger amount, CallOptions options = default);
		
		[EvmMethodInfo(Name = "withdrawYield", View = false)]
		Task<Transaction> WithdrawYield();
		
	}
}
