//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  Contract2.sol
//   Output filename: Contract2.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace Contract2
{
	#if UNITY_EDITOR || !ENABLE_MONO
	[BackedType(typeof(Contract2Backing))]
	#endif
	public interface Contract2 : IContract
	{
		[EvmConstructorMethod]
		Task<Contract2> DeployNew();
		
		[EvmMethodInfo(Name = "blast", View = true)]
		Task<EvmAddress> Blast();
		
		[EvmMethodInfo(Name = "getAvailableYield", View = true)]
		Task<BigInteger> GetAvailableYield();
		
		[EvmMethodInfo(Name = "getBalance", View = true)]
		Task<BigInteger> GetBalance();
		
		[EvmMethodInfo(Name = "withdraw", View = false)]
		Task<Transaction> Withdraw(BigInteger amount, CallOptions options = default);
		
		[EvmMethodInfo(Name = "withdrawYield", View = false)]
		Task<Transaction> WithdrawYield();
		
	}
}
